import { name, version } from "../package.json";

export const appName = name;
export const appVersion = version;
export const dataPerPage = 8;

export const projectTypeOptions = [
  {
    value: "angular",
    name: "Angular",
    hint: "Deliver web apps with confidence",
    cli: "npm init @angular",
    category: "JS",
    label: "",
  },
  {
    value: "nextjs",
    name: "Next.js",
    hint: "The React framework for the web",
    cli: "npx create-next-app@latest",
    category: "JS",
    label: "",
  },
  {
    value: "nuxt",
    name: "Nuxt.js",
    hint: "The intuitive Vue framework",
    cli: "npx create-nuxt-app",
    category: "JS",
    label: "",
  },
  {
    value: "remix",
    name: "Remix",
    hint: "Build better websites. Create modern, resilient user experiences with web fundamentals",
    cli: "npx create-remix@latest",
    category: "JS",
    label: "",
  },
  {
    value: "svelte",
    name: "SvelteKit",
    hint: "Rapidly developing robust, performant web applications using Svelte",
    cli: "npm create svelte@latest",
    category: "JS",
    label: "",
  },
  {
    value: "vuejs",
    name: "Vue.js",
    hint: "The progressive JavaScript framework",
    cli: "npm init vue@latest",
    category: "JS",
    label: "",
  },
  {
    value: "astro",
    name: "Astro",
    hint: "Build the web you want",
    cli: "npm create astro@latest",
    category: "JS",
    label: "",
  },
  {
    value: "nestjs",
    name: "NestJS",
    hint: "A progressive Node.js framework",
    cli: "npx nest new",
    category: "JS",
    label: "",
  },
  {
    value: "emberjs",
    name: "Ember.js",
    hint: "A framework for ambitious web developers",
    cli: "npx ember new",
    category: "JS",
    label: "",
  },
  {
    value: "gatsby",
    name: "Gatsby",
    hint: "The fastest frontend for the headless web",
    cli: "npx gatsby new",
    category: "JS",
    label: "",
  },
  {
    value: "qwik",
    name: "Qwik",
    hint: "Framework reimagined for the edge!",
    cli: "npm create qwik@latest",
    category: "JS",
    label: "",
  },
  {
    value: "sails",
    name: "Sails",
    hint: "Realtime MVC framework for Node.js",
    cli: "npx sails new",
    category: "JS",
    label: "",
  },
  {
    value: "vite",
    name: "Vite",
    hint: "Next Generation Frontend Tooling",
    cli: "npm create vite@latest",
    category: "JS",
    label: "",
  },
  {
    value: "aurelia",
    name: "Aurelia",
    hint: "Simple. Powerful. Unobtrusive.",
    cli: "npx aurelia-cli new",
    category: "JS",
    label: "",
  },
  {
    value: "solidstart",
    name: "SolidStart",
    hint: "The Solid app framework",
    cli: "npm init solid@latest",
    category: "JS",
    label: "",
  },
  {
    value: "preact",
    name: "Preact",
    hint: "A different kind of library",
    cli: "npx preact-cli create default",
    category: "JS",
    label: "",
  },
  {
    value: "createreactapp",
    name: "React (create-react-app/CRA)",
    hint: "Set up a modern web app by running one command",
    cli: "npx create-react-app",
    category: "JS",
    label: "",
  },
  {
    value: "adonisjs",
    name: "AdonisJS",
    hint: "A fully featured web framework for Node.js",
    cli: "npm init adonis-ts-app@latest",
    category: "JS",
    label: "",
  },
  {
    value: "solidjs",
    name: "SolidJS",
    hint: "Reactive Javascript Library",
    cli: "",
    category: "JS",
    label: "",
  },
  {
    value: "stencil",
    name: "Stencil",
    hint: "Build. Customize. Distribute. Adopt.",
    cli: "npm init stencil",
    category: "JS",
    label: "",
  },
  {
    value: "quasar",
    name: "Quasar",
    hint: "The enterprise-ready cross-platform VueJs framework",
    cli: "npm init quasar",
    category: "JS",
    label: "",
  },
  {
    value: "inferno",
    name: "Inferno",
    hint: "An extremely fast, React-like JavaScript library",
    cli: "npx degit infernojs/inferno-boilerplate",
    category: "JS",
    label: "",
  },
  {
    value: "reactredux",
    name: "React Redux",
    hint: "A predictable state container for JavaScript apps",
    cli: "",
    category: "JS",
    label: "",
  },
  {
    value: "expressjs",
    name: "Express.js",
    hint: "Node.js web application framework",
    cli: "npx express-generator",
    category: "JS",
    label: "",
  },
  {
    value: "nx",
    name: "Nx",
    hint: "Smart, fast and extensible build system",
    cli: "npx create-nx-workspace@latest",
    category: "JS",
    label: "",
  },
  {
    value: "blitzjs",
    name: "Blitz.js",
    hint: "The missing fullstack toolkit for Next.js",
    cli: "npx blitz new",
    category: "JS",
    label: "",
  },
  {
    value: "vitepress",
    name: "VitePress",
    hint: "Vite & Vue powered static site generator",
    cli: "npx vitepress init",
    category: "JS",
    label: "",
  },
  {
    value: "openwebcomponents",
    name: "Open Web Components",
    hint: "Web component project scaffolding",
    cli: "npm init @open-wc",
    category: "JS",
    label: "",
  },
  {
    value: "docusaurus",
    name: "Docusaurus",
    hint: "Build optimized websites quickly, focus on your content",
    cli: "npx create-docusaurus@latest",
    category: "JS",
    label: "",
  },
  {
    value: "hexo",
    name: "Hexo",
    hint: "A fast, simple & powerful blog framework",
    cli: "npx hexo-cli init",
    category: "JS",
    label: "",
  },
  {
    value: "vuepress",
    name: "VuePress",
    hint: "Vue-powered static site generator",
    cli: "npx create-vuepress-site",
    category: "JS",
    label: "",
  },
  {
    value: "gridsome",
    name: "Gridsome",
    hint: "Modern site generator for Vue.js",
    cli: "npx @gridsome/cli create",
    category: "JS",
    label: "",
  },
  {
    value: "analogjs",
    name: "Analog",
    hint: "The fullstack Angular meta-framework",
    cli: "npm create analog@latest",
    category: "JS",
    label: "",
  },
  {
    value: "nitro",
    name: "Nitro",
    hint: "Create web servers that run anywhere",
    cli: "npx giget@latest nitro",
    category: "JS",
    label: "",
  },
  {
    value: "redwoodjs",
    name: "RedwoodJS",
    hint: "The app framework for startups",
    cli: "npx create-redwood-app",
    category: "JS",
    label: "",
  },
];
