import { name, version } from "../package.json";

export const appName = name;
export const appVersion = version;
export const dataPerPage = 8;

export const projectTypeOptions = [
  {
    value: "angular",
    name: "Angular",
    hint: "Deliver web apps with confidence",
    cli: "npm init @angular",
    category: "JS",
  },
  {
    value: "nextjs",
    name: "Next.js",
    hint: "The React framework for the web",
    cli: "npx create-next-app@latest",
    category: "JS",
  },
  {
    value: "nuxt",
    name: "Nuxt.js",
    hint: "The intuitive Vue framework",
    cli: "npx create-nuxt-app",
    category: "JS",
  },
  {
    value: "remix",
    name: "Remix",
    hint: "Build better websites. Create modern, resilient user experiences with web fundamentals",
    cli: "npx create-remix@latest",
    category: "JS",
  },
  {
    value: "svelte",
    name: "SvelteKit",
    hint: "Rapidly developing robust, performant web applications using Svelte",
    cli: "npm create svelte@latest",
    category: "JS",
  },
  {
    value: "vuejs",
    name: "Vue.js",
    hint: "The progressive JavaScript framework",
    cli: "npm init vue@latest",
    category: "JS",
  },
  {
    value: "astro",
    name: "Astro",
    hint: "Build the web you want",
    cli: "npm create astro@latest",
    category: "JS",
  },
  {
    value: "nestjs",
    name: "NestJS",
    hint: "A progressive Node.js framework",
    cli: "npx nest new",
    category: "JS",
  },
  {
    value: "emberjs",
    name: "Ember.js",
    hint: "A framework for ambitious web developers",
    cli: "npx ember new",
    category: "JS",
  },
  {
    value: "gatsby",
    name: "Gatsby",
    hint: "The fastest frontend for the headless web",
    cli: "npx gatsby new",
    category: "JS",
  },
  {
    value: "qwik",
    name: "Qwik",
    hint: "Framework reimagined for the edge!",
    cli: "npm create qwik@latest",
    category: "JS",
  },
  {
    value: "sails",
    name: "Sails",
    hint: "Realtime MVC framework for Node.js",
    cli: "npx sails new",
    category: "JS",
  },
  {
    value: "vite",
    name: "Vite",
    hint: "Next Generation Frontend Tooling",
    cli: "npm create vite@latest",
    category: "JS",
  },
  {
    value: "aurelia",
    name: "Aurelia",
    hint: "Simple. Powerful. Unobtrusive.",
    cli: "npx aurelia-cli new",
    category: "JS",
  },
  {
    value: "solidstart",
    name: "SolidStart",
    hint: "The Solid app framework",
    cli: "npm init solid@latest",
    category: "JS",
  },
  {
    value: "preact",
    name: "Preact",
    hint: "A different kind of library",
    cli: "npx preact-cli create default",
    category: "JS",
  },
  {
    value: "createreactapp",
    name: "React (create-react-app/CRA)",
    hint: "Set up a modern web app by running one command",
    cli: "npx create-react-app",
    category: "JS",
  },
  {
    value: "adonisjs",
    name: "AdonisJS",
    hint: "A fully featured web framework for Node.js",
    cli: "npm init adonis-ts-app@latest",
    category: "JS",
  },
  {
    value: "solidjs",
    name: "SolidJS",
    hint: "Reactive Javascript Library",
    cli: "",
    category: "JS",
  },
  {
    value: "inferno",
    name: "Inferno",
    hint: "An extremely fast, React-like JavaScript library",
    cli: "npx degit infernojs/inferno-boilerplate",
    category: "JS",
  },
  {
    value: "reactredux",
    name: "React Redux",
    hint: "A predictable state container for JavaScript apps",
    cli: "",
    category: "JS",
  },
  {
    value: "expressjs",
    name: "Express.js",
    hint: "Node.js web application framework",
    cli: "npx express-generator",
    category: "JS",
  },
  {
    value: "nx",
    name: "Nx",
    hint: "Smart, fast and extensible build system",
    cli: "npx create-nx-workspace@latest",
    category: "JS",
  },
];
